on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  docker-container:
    name: Publish Docker container
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            BOT_VER=${{ github.ref_name }}
          tags: ghcr.io/caphosra/cthulhu-bot:${{ github.ref_name }}
