on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

name: Test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.71.0
      - uses: actions-rs/cargo@v1
        with:
          command: test
